<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="compy-386" name="org.gdejohn.similitude.ClonerTest" tests="1" failures="0" timestamp="24 Apr 2012 21:48:39 GMT" time="0.036" errors="1">
  <testcase name="testEnclosingGeneric" time="0.036" classname="org.gdejohn.similitude.ClonerTest">
    <error type="java.lang.AssertionError" message="Failed.">
      <![CDATA[java.lang.AssertionError: Failed.
	at org.testng.Assert.fail(Assert.java:78)
	at org.gdejohn.similitude.ClonerTest.testEnclosingGeneric(ClonerTest.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1022)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:109)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:202)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:173)
Caused by: java.lang.RuntimeException
	at org.gdejohn.similitude.TypeToken.typeOf(TypeToken.java:491)
	at org.gdejohn.similitude.TypeToken.typeOf(TypeToken.java:477)
	at org.gdejohn.similitude.TypeToken.typeOf(TypeToken.java:477)
	at org.gdejohn.similitude.ClonerTest.testEnclosingGeneric(ClonerTest.java:120)
	... 24 more
]]>
    </error>
  </testcase> <!-- testEnclosingGeneric -->
</testsuite> <!-- org.gdejohn.similitude.ClonerTest -->
